services:
  reg:
    image: images.opencadc.org/core/reg:1.1.0
    container_name: reg
    user: "tomcat:tomcat"
    ports:
      - "8881:8080"
    volumes:
      - ./config/reg:/config
      - ./config/cacerts:/config/cacerts
    networks:
      - mynetwork

  baldur:
    image: stephenlloyd/uksrc:baldur
    container_name: baldur
    user: "tomcat:tomcat"
    ports:
      - "8882:8080"
    volumes:
      - ./config/baldur:/config
      - ./config/cacerts:/config/cacerts
    networks:
      - mynetwork

  pg15test:
    image: stephenlloyd/uksrc:cadc-postgresql-dev
    container_name: pg15test
    ports:
      - "5432:5432"
    volumes:
      - ./config/postgres:/config
      - ./config/cacerts:/config/cacerts
    restart: always
    networks:
      - mynetwork

  torkeep:
    image: images.opencadc.org/caom2/torkeep:0.1.4
    container_name: torkeep
    user: "tomcat:tomcat"
    ports:
      - "8883:8080"
    volumes:
      - ./config/torkeep:/config
      - ./config/cacerts:/config/cacerts
      - ./config/cadc-registry.properties:/config/cadc-registry.properties:ro
      - ./logs:/logs:ro
    networks:
      - mynetwork

  nginx:
    image: nginx:latest
    network_mode: "host"
    container_name: nginx
    volumes:
      - ./config/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./ssl/server.crt:/etc/nginx/ssl/server.crt
      - ./ssl/server.key:/etc/nginx/ssl/server.key

networks:
  mynetwork:
    driver: bridge
